name: My First Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t my-first-app .

      - name: Run the container
        run: docker run my-first-app
